### ISSUE TITLE
关于 1984 的评论 希望多思考下

### ISSUE THREAD

**Issue by Kuangcp** [leosanqing/Java-Notes#7]
[【从书说起】这本书，可以说是“公知从入门到精通”必读了](https://www.bilibili.com/video/BV1FK4y147fz)
[【从书说起】《一九八四》，其实还是部虐恋小说？](https://www.bilibili.com/video/BV1PV411k7XF)

**Comment by leosanqing** [comment]
本来打了很多字，想了想还是 换成 "厉害了，我的国" 吧
